project:
  type: website
  output-dir: docs


website:
  title: "Blog Pessoal"
  site-url: https://mwillian.github.io 
  favicon: favicon.png
  navbar:
    right:
      - href: index.qmd
        text: Início
      - href: about\about.qmd
        text: Sobre
      - href: projects\index.qmd
        text: Projetos
      - href: cursos\cursos.qmd
        text: Cursos
      - href: eventos\eventos.qmd
        text: Eventos e Atuações
      - href: contato.qmd
        text: Contato
      - icon: github
        href: https://github.com/MWillian
        target: _blank
      - icon: linkedin
        href: https://linkedin.com
        target: _blank
format:
  html:
    theme: darkly  
    css: styles.css
    lightbox: true
