project:
  type: website
  output-dir: docs


website:
  description: "Matheus Willian - Dev"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Matheus Willian"
  navbar:
    right:
      - href: about\about.qmd
        text: Sobre
      - href: projects\index.qmd
        text: Projetos
      - icon: github
        href: https://github.com/MWillian
      - icon: linkedin
        href: https://linkedin.com
format:
  html:
    theme: darkly  
    css: styles.css
    lightbox: true
